language: bash

install:
  - rm -rf public/
  - echo "Cleaned up public folder..."
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
  - sudo dpkg -i hugo_0.55.4_Linux-64bit.deb

script:
  - hugo
  - echo "Hugo build successful"

deploy:
  provider: pages
  script: ./deploy.sh
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master